theme: jekyll-theme-minimal
author: odelay.tomato
title: odelay-tomato
description: I’m a husband, dad, and amateur windsock calibrator. Sometimes I write about thoughts or feelings or ideas I have on different subjects. Maybe it’s a place to just practice writing?
email: odelay.tomato@gmail.com
